// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillSphere.Infrastructure.Persistence;

#nullable disable

namespace SkillSphere.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SkillSphereDbContext))]
    partial class SkillSphereDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillSphere.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolTenantId");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("SessionTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("StudentProfileId", "SubjectId", "Date", "SessionTime");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<Guid?>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.BehaviorFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("TeacherProfileId");

                    b.ToTable("BehaviorFeedbacks");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ClassSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("SchoolTenantId");

                    b.ToTable("ClassSections");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("FeatureType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId", "FeatureType")
                        .IsUnique();

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.GradeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssessmentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LetterGrade")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId");

                    b.ToTable("GradeRecords");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.InternalReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedSupervisorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrls")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EscalatedToUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReporterTeacherProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSupervisorId");

                    b.HasIndex("EscalatedToUserId");

                    b.HasIndex("ReporterTeacherProfileId");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("InternalReports");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.InternalReportComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("InternalReportId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDecisionNote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("InternalReportId");

                    b.ToTable("InternalReportComments");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.NotificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("TemplateData")
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("SchoolTenantId");

                    b.ToTable("NotificationEvents");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ParentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParentProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("ParentProfileId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("ParentLinks");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ParentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ParentProfiles");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.PerformanceAttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.ToTable("PerformanceAttributeDefinitions");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.SchoolTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SchoolTenants");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.StudentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("GradeId");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentProfileId", "SemesterId")
                        .IsUnique();

                    b.ToTable("StudentAssignments");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SchoolTenantId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.SupervisorScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GradeId");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId");

                    b.ToTable("SupervisorScopes");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("GradeId");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId", "SubjectId", "ClassSectionId", "SemesterId")
                        .IsUnique();

                    b.ToTable("TeacherAssignments");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TeacherProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TeacherProfiles");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TimetableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Room")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimetableVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("GradeId");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("TimetableVersionId");

                    b.ToTable("TimetableEntries");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TimetableVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SemesterId");

                    b.ToTable("TimetableVersions");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.WeeklyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DistributedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SchoolTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTenantId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("StudentProfileId", "SubjectId", "SemesterId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("WeeklyReports");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.WeeklyReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumericValue")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyReportId");

                    b.ToTable("WeeklyReportItems");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany("Users")
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany()
                        .HasForeignKey("ClassSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSection");

                    b.Navigation("SchoolTenant");

                    b.Navigation("Semester");

                    b.Navigation("StudentProfile");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId");

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.BehaviorFeedback", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("BehaviorFeedbacks")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");

                    b.Navigation("Semester");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ClassSection", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.Grade", "Grade")
                        .WithMany("ClassSections")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany("ClassSections")
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Department", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany("Departments")
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.FeatureFlag", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Grade", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany("Grades")
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.GradeRecord", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("GradeRecords")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");

                    b.Navigation("Semester");

                    b.Navigation("StudentProfile");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.InternalReport", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "AssignedSupervisor")
                        .WithMany()
                        .HasForeignKey("AssignedSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillSphere.Domain.Entities.ApplicationUser", "EscalatedToUser")
                        .WithMany()
                        .HasForeignKey("EscalatedToUserId");

                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "ReporterTeacher")
                        .WithMany()
                        .HasForeignKey("ReporterTeacherProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId");

                    b.Navigation("AssignedSupervisor");

                    b.Navigation("EscalatedToUser");

                    b.Navigation("ReporterTeacher");

                    b.Navigation("SchoolTenant");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.InternalReportComment", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.ApplicationUser", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.InternalReport", "InternalReport")
                        .WithMany("Comments")
                        .HasForeignKey("InternalReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("InternalReport");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.NotificationEvent", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.ApplicationUser", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ParentLink", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.ParentProfile", "ParentProfile")
                        .WithMany("ParentLinks")
                        .HasForeignKey("ParentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ParentLinks")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentProfile");

                    b.Navigation("SchoolTenant");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ParentProfile", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.ApplicationUser", "User")
                        .WithOne("ParentProfile")
                        .HasForeignKey("SkillSphere.Domain.Entities.ParentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.PerformanceAttributeDefinition", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Semester", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany("Semesters")
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.StudentAssignment", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("ClassSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Grade", "Grade")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Semester", "Semester")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("Assignments")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSection");

                    b.Navigation("Grade");

                    b.Navigation("SchoolTenant");

                    b.Navigation("Semester");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.ApplicationUser", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("SkillSphere.Domain.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Subject", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("SchoolTenant");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.SupervisorScope", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany()
                        .HasForeignKey("ClassSectionId");

                    b.HasOne("SkillSphere.Domain.Entities.Department", "Department")
                        .WithMany("SupervisorScopes")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("SkillSphere.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId");

                    b.HasOne("SkillSphere.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany("SupervisorScopes")
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSection");

                    b.Navigation("Department");

                    b.Navigation("Grade");

                    b.Navigation("SchoolTenant");

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TeacherAssignment", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("ClassSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Grade", "Grade")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Semester", "Semester")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Subject", "Subject")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany("Assignments")
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSection");

                    b.Navigation("Grade");

                    b.Navigation("SchoolTenant");

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TeacherProfile", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.ApplicationUser", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("SkillSphere.Domain.Entities.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TimetableEntry", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany("TimetableEntries")
                        .HasForeignKey("ClassSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Subject", "Subject")
                        .WithMany("TimetableEntries")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany("TimetableEntries")
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.TimetableVersion", "TimetableVersion")
                        .WithMany("Entries")
                        .HasForeignKey("TimetableVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSection");

                    b.Navigation("Grade");

                    b.Navigation("SchoolTenant");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");

                    b.Navigation("TimetableVersion");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TimetableVersion", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Semester", "Semester")
                        .WithMany("TimetableVersions")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.WeeklyReport", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.SchoolTenant", "SchoolTenant")
                        .WithMany()
                        .HasForeignKey("SchoolTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Semester", "Semester")
                        .WithMany("WeeklyReports")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("WeeklyReports")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSphere.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTenant");

                    b.Navigation("Semester");

                    b.Navigation("StudentProfile");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.WeeklyReportItem", b =>
                {
                    b.HasOne("SkillSphere.Domain.Entities.WeeklyReport", "WeeklyReport")
                        .WithMany("Items")
                        .HasForeignKey("WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ParentProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ClassSection", b =>
                {
                    b.Navigation("StudentAssignments");

                    b.Navigation("TeacherAssignments");

                    b.Navigation("TimetableEntries");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Department", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("SupervisorScopes");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Grade", b =>
                {
                    b.Navigation("ClassSections");

                    b.Navigation("StudentAssignments");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.InternalReport", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.ParentProfile", b =>
                {
                    b.Navigation("ParentLinks");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.SchoolTenant", b =>
                {
                    b.Navigation("ClassSections");

                    b.Navigation("Departments");

                    b.Navigation("FeatureFlags");

                    b.Navigation("Grades");

                    b.Navigation("Semesters");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Semester", b =>
                {
                    b.Navigation("StudentAssignments");

                    b.Navigation("TeacherAssignments");

                    b.Navigation("TimetableVersions");

                    b.Navigation("WeeklyReports");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.StudentProfile", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("BehaviorFeedbacks");

                    b.Navigation("GradeRecords");

                    b.Navigation("ParentLinks");

                    b.Navigation("WeeklyReports");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.Subject", b =>
                {
                    b.Navigation("TeacherAssignments");

                    b.Navigation("TimetableEntries");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TeacherProfile", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("SupervisorScopes");

                    b.Navigation("TimetableEntries");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.TimetableVersion", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SkillSphere.Domain.Entities.WeeklyReport", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
